<?php

namespace AppBundle\Repository;

use Doctrine\ORM\Query\Expr\Join;

/**
 * ProductOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductOrderRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAll($filters = []) {
        $qb = $this->createQueryBuilder('por')
            ->select([
                'por.id',
                'por.orderId',
                'por.orderStatus',
                'p.id as product_id',
                'p.name',
                'b.id as box_id'
            ])
            ->leftJoin('por.product', 'p')
            ->leftJoin('por.box', 'b');
            ;

        if (isset($filters['search'])) {
            $qb->where('por.orderId LIKE :orderId')
                ->setParameter('orderId', '%' . $filters['search']['value'] . '%');
        }

        return $qb->getQuery()->getResult();
    }
}
